//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4952
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://escience.ifmo.ru/nasis/eventing/WFStateUpdatedEvent.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://escience.ifmo.ru/nasis/eventing/WFStateUpdatedEvent.xsd", IsNullable=false)]
public partial class WFStateUpdatedEvent {
    
    private WFStateUpdatedTypeEnum wFStateUpdatedTypeField;
    
    private string systemInfoField;
    
    private string commentField;
    
    private string wFRunCodeField;
    
    private string wFStepCodeField;
    
    /// <remarks/>
    public WFStateUpdatedTypeEnum WFStateUpdatedType {
        get {
            return this.wFStateUpdatedTypeField;
        }
        set {
            this.wFStateUpdatedTypeField = value;
        }
    }
    
    /// <remarks/>
    public string SystemInfo {
        get {
            return this.systemInfoField;
        }
        set {
            this.systemInfoField = value;
        }
    }
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public string WFRunCode {
        get {
            return this.wFRunCodeField;
        }
        set {
            this.wFRunCodeField = value;
        }
    }
    
    /// <remarks/>
    public string WFStepCode {
        get {
            return this.wFStepCodeField;
        }
        set {
            this.wFStepCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://escience.ifmo.ru/nasis/eventing/WFStateUpdatedEvent.xsd")]
public enum WFStateUpdatedTypeEnum {
    
    /// <remarks/>
    WFStepStarted,
    
    /// <remarks/>
    WFStepFinished,
    
    /// <remarks/>
    WFStepError,
}
