//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoDB.Bson
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ObjectId", Namespace = "http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    public partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int _incrementField;

        private int _machineField;

        private short _pidField;

        private int _timestampField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int _increment
        {
            get
            {
                return this._incrementField;
            }
            set
            {
                this._incrementField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int _machine
        {
            get
            {
                return this._machineField;
            }
            set
            {
                this._machineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public short _pid
        {
            get
            {
                return this._pidField;
            }
            set
            {
                this._pidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int _timestamp
        {
            get
            {
                return this._timestampField;
            }
            set
            {
                this._timestampField = value;
            }
        }
    }
}

namespace MonitoringFacade
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IMonitoringService")]
    public interface IMonitoringService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetActualDataInJson", ReplyAction = "http://tempuri.org/IMonitoringService/GetActualDataInJsonResponse")]
        string GetActualDataInJson(string infoPath);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetJobInfoInJson", ReplyAction = "http://tempuri.org/IMonitoringService/GetJobInfoInJsonResponse")]
        string GetJobInfoInJson(System.Guid jid);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetResourcesInfoInJson", ReplyAction = "http://tempuri.org/IMonitoringService/GetResourcesInfoInJsonResponse")]
        string GetResourcesInfoInJson();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetResourcesInfo", ReplyAction = "http://tempuri.org/IMonitoringService/GetResourcesInfoResponse")]
        Easis.Common.DataContracts.ResourceDescription GetResourcesInfo();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetJobInfo", ReplyAction = "http://tempuri.org/IMonitoringService/GetJobInfoResponse")]
        Easis.Common.DataContracts.JobDescription GetJobInfo(System.Guid jid);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/PutJobResultInBson", ReplyAction = "http://tempuri.org/IMonitoringService/PutJobResultInBsonResponse")]
        void PutJobResultInBson(byte[] jr);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/PutJobResult", ReplyAction = "http://tempuri.org/IMonitoringService/PutJobResultResponse")]
        void PutJobResult(Easis.Common.DataContracts.JobDescription jd);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMonitoringService/GetHistoryInJson", ReplyAction = "http://tempuri.org/IMonitoringService/GetHistoryInJsonResponse")]
        string GetHistoryInJson(string infoPath, System.DateTime from, System.DateTime to);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : IMonitoringService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<IMonitoringService>, IMonitoringService
    {

        public MonitoringServiceClient()
        {
        }

        public MonitoringServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string GetActualDataInJson(string infoPath)
        {
            return base.Channel.GetActualDataInJson(infoPath);
        }

        public string GetJobInfoInJson(System.Guid jid)
        {
            return base.Channel.GetJobInfoInJson(jid);
        }

        public string GetResourcesInfoInJson()
        {
            return base.Channel.GetResourcesInfoInJson();
        }

        public Easis.Common.DataContracts.ResourceDescription GetResourcesInfo()
        {
            return base.Channel.GetResourcesInfo();
        }

        public Easis.Common.DataContracts.JobDescription GetJobInfo(System.Guid jid)
        {
            return base.Channel.GetJobInfo(jid);
        }

        public void PutJobResultInBson(byte[] jr)
        {
            base.Channel.PutJobResultInBson(jr);
        }

        public void PutJobResult(Easis.Common.DataContracts.JobDescription jd)
        {
            base.Channel.PutJobResult(jd);
        }

        public string GetHistoryInJson(string infoPath, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetHistoryInJson(infoPath, from, to);
        }
    }
}