//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalEventListener.PES {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/PES/SequenceService", ConfigurationName="PES.SequenceServiceSoap")]
    public interface SequenceServiceSoap {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://localhost/PES/SequenceService)
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/SequenceEstimate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExternalEventListener.PES.SequenceEstimateResponse SequenceEstimate(ExternalEventListener.PES.SequenceEstimateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/SequenceRun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SequenceRun(string sequenceRunXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/Debug", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Debug();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/SequenceAbort", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SequenceAbort(ulong sequenceId);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://localhost/PES/SequenceService)
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/SequenceGetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExternalEventListener.PES.SequenceGetInfoResponse SequenceGetInfo(ExternalEventListener.PES.SequenceGetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/SequenceGetInfoInXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SequenceGetInfoInXml(ulong sequenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/GetLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/GetLogInHtml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLogInHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/PES/SequenceService/TaskComplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TaskComplete(string TaskId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SequenceEstimateResultTime timeField;
        
        private SequenceEstimateResultStep[] stepField;
        
        private ulong idField;
        
        private stepResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SequenceEstimateResultTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", Order=1)]
        public SequenceEstimateResultStep[] step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
                this.RaisePropertyChanged("step");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime stampField;
        
        private ulong elapsedField;
        
        private ulong wastedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
                this.RaisePropertyChanged("stamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
                this.RaisePropertyChanged("elapsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong wasted {
            get {
                return this.wastedField;
            }
            set {
                this.wastedField = value;
                this.RaisePropertyChanged("wasted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
                this.RaisePropertyChanged("estimatedMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
                this.RaisePropertyChanged("estimatedMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStep : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SequenceEstimateResultStepTime timeField;
        
        private SequenceEstimateResultStepCluster clusterField;
        
        private SequenceEstimateResultStepIN[] inField;
        
        private SequenceEstimateResultStepOut[] outField;
        
        private string taskIdField;
        
        private uint orderField;
        
        private stepResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SequenceEstimateResultStepTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SequenceEstimateResultStepCluster cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
                this.RaisePropertyChanged("cluster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("in", Order=2)]
        public SequenceEstimateResultStepIN[] @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
                this.RaisePropertyChanged("in");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("out", Order=3)]
        public SequenceEstimateResultStepOut[] @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong elapsedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
                this.RaisePropertyChanged("elapsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
                this.RaisePropertyChanged("estimatedMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
                this.RaisePropertyChanged("estimatedMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepCluster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string appField;
        
        private uint nodeCountField;
        
        private bool nodeCountFieldSpecified;
        
        private uint coreCountField;
        
        private bool coreCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string app {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
                this.RaisePropertyChanged("app");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint nodeCount {
            get {
                return this.nodeCountField;
            }
            set {
                this.nodeCountField = value;
                this.RaisePropertyChanged("nodeCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeCountSpecified {
            get {
                return this.nodeCountFieldSpecified;
            }
            set {
                this.nodeCountFieldSpecified = value;
                this.RaisePropertyChanged("nodeCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint coreCount {
            get {
                return this.coreCountField;
            }
            set {
                this.coreCountField = value;
                this.RaisePropertyChanged("coreCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coreCountSpecified {
            get {
                return this.coreCountFieldSpecified;
            }
            set {
                this.coreCountFieldSpecified = value;
                this.RaisePropertyChanged("coreCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepIN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
                this.RaisePropertyChanged("internalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
                this.RaisePropertyChanged("storageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
                this.RaisePropertyChanged("slotName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
                this.RaisePropertyChanged("internalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
                this.RaisePropertyChanged("storageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
                this.RaisePropertyChanged("slotName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum stepResult {
        
        /// <remarks/>
        completed,
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        notStarted,
        
        /// <remarks/>
        started,
        
        /// <remarks/>
        aborted,
        
        /// <remarks/>
        timeLimitExceeded,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SequenceEstimate", WrapperNamespace="http://localhost/PES/SequenceService", IsWrapped=true)]
    public partial class SequenceEstimateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/PES/SequenceService", Order=0)]
        public string sequenceRunXml;
        
        public SequenceEstimateRequest() {
        }
        
        public SequenceEstimateRequest(string sequenceRunXml) {
            this.sequenceRunXml = sequenceRunXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SequenceEstimateResponse", WrapperNamespace="http://localhost/PES/SequenceService", IsWrapped=true)]
    public partial class SequenceEstimateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ExternalEventListener.PES.SequenceEstimateResult SequenceEstimateResult;
        
        public SequenceEstimateResponse() {
        }
        
        public SequenceEstimateResponse(ExternalEventListener.PES.SequenceEstimateResult SequenceEstimateResult) {
            this.SequenceEstimateResult = SequenceEstimateResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SequenceGetInfoResultTime timeField;
        
        private SequenceGetInfoResultStep[] stepField;
        
        private ulong idField;
        
        private stepResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SequenceGetInfoResultTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", Order=1)]
        public SequenceGetInfoResultStep[] step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
                this.RaisePropertyChanged("step");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime stampField;
        
        private ulong elapsedField;
        
        private ulong wastedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
                this.RaisePropertyChanged("stamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
                this.RaisePropertyChanged("elapsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong wasted {
            get {
                return this.wastedField;
            }
            set {
                this.wastedField = value;
                this.RaisePropertyChanged("wasted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
                this.RaisePropertyChanged("estimatedMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
                this.RaisePropertyChanged("estimatedMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStep : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SequenceGetInfoResultStepTime timeField;
        
        private SequenceGetInfoResultStepCluster clusterField;
        
        private SequenceGetInfoResultStepIN[] inField;
        
        private SequenceGetInfoResultStepOut[] outField;
        
        private string taskIdField;
        
        private uint orderField;
        
        private stepResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SequenceGetInfoResultStepTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SequenceGetInfoResultStepCluster cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
                this.RaisePropertyChanged("cluster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("in", Order=2)]
        public SequenceGetInfoResultStepIN[] @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
                this.RaisePropertyChanged("in");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("out", Order=3)]
        public SequenceGetInfoResultStepOut[] @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong elapsedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
                this.RaisePropertyChanged("elapsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
                this.RaisePropertyChanged("estimatedMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
                this.RaisePropertyChanged("estimatedMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepCluster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string appField;
        
        private uint nodeCountField;
        
        private bool nodeCountFieldSpecified;
        
        private uint coreCountField;
        
        private bool coreCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string app {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
                this.RaisePropertyChanged("app");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint nodeCount {
            get {
                return this.nodeCountField;
            }
            set {
                this.nodeCountField = value;
                this.RaisePropertyChanged("nodeCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeCountSpecified {
            get {
                return this.nodeCountFieldSpecified;
            }
            set {
                this.nodeCountFieldSpecified = value;
                this.RaisePropertyChanged("nodeCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint coreCount {
            get {
                return this.coreCountField;
            }
            set {
                this.coreCountField = value;
                this.RaisePropertyChanged("coreCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coreCountSpecified {
            get {
                return this.coreCountFieldSpecified;
            }
            set {
                this.coreCountFieldSpecified = value;
                this.RaisePropertyChanged("coreCountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepIN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
                this.RaisePropertyChanged("internalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
                this.RaisePropertyChanged("storageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
                this.RaisePropertyChanged("slotName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
                this.RaisePropertyChanged("internalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
                this.RaisePropertyChanged("storageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
                this.RaisePropertyChanged("slotName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SequenceGetInfo", WrapperNamespace="http://localhost/PES/SequenceService", IsWrapped=true)]
    public partial class SequenceGetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/PES/SequenceService", Order=0)]
        public ulong sequenceId;
        
        public SequenceGetInfoRequest() {
        }
        
        public SequenceGetInfoRequest(ulong sequenceId) {
            this.sequenceId = sequenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SequenceGetInfoResponse", WrapperNamespace="http://localhost/PES/SequenceService", IsWrapped=true)]
    public partial class SequenceGetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ExternalEventListener.PES.SequenceGetInfoResult SequenceGetInfoResult;
        
        public SequenceGetInfoResponse() {
        }
        
        public SequenceGetInfoResponse(ExternalEventListener.PES.SequenceGetInfoResult SequenceGetInfoResult) {
            this.SequenceGetInfoResult = SequenceGetInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SequenceServiceSoapChannel : ExternalEventListener.PES.SequenceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SequenceServiceSoapClient : System.ServiceModel.ClientBase<ExternalEventListener.PES.SequenceServiceSoap>, ExternalEventListener.PES.SequenceServiceSoap {
        
        public SequenceServiceSoapClient() {
        }
        
        public SequenceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SequenceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalEventListener.PES.SequenceEstimateResponse ExternalEventListener.PES.SequenceServiceSoap.SequenceEstimate(ExternalEventListener.PES.SequenceEstimateRequest request) {
            return base.Channel.SequenceEstimate(request);
        }
        
        public ExternalEventListener.PES.SequenceEstimateResult SequenceEstimate(string sequenceRunXml) {
            ExternalEventListener.PES.SequenceEstimateRequest inValue = new ExternalEventListener.PES.SequenceEstimateRequest();
            inValue.sequenceRunXml = sequenceRunXml;
            ExternalEventListener.PES.SequenceEstimateResponse retVal = ((ExternalEventListener.PES.SequenceServiceSoap)(this)).SequenceEstimate(inValue);
            return retVal.SequenceEstimateResult;
        }
        
        public void SequenceRun(string sequenceRunXml) {
            base.Channel.SequenceRun(sequenceRunXml);
        }
        
        public void Debug() {
            base.Channel.Debug();
        }
        
        public void SequenceAbort(ulong sequenceId) {
            base.Channel.SequenceAbort(sequenceId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExternalEventListener.PES.SequenceGetInfoResponse ExternalEventListener.PES.SequenceServiceSoap.SequenceGetInfo(ExternalEventListener.PES.SequenceGetInfoRequest request) {
            return base.Channel.SequenceGetInfo(request);
        }
        
        public ExternalEventListener.PES.SequenceGetInfoResult SequenceGetInfo(ulong sequenceId) {
            ExternalEventListener.PES.SequenceGetInfoRequest inValue = new ExternalEventListener.PES.SequenceGetInfoRequest();
            inValue.sequenceId = sequenceId;
            ExternalEventListener.PES.SequenceGetInfoResponse retVal = ((ExternalEventListener.PES.SequenceServiceSoap)(this)).SequenceGetInfo(inValue);
            return retVal.SequenceGetInfoResult;
        }
        
        public string SequenceGetInfoInXml(ulong sequenceId) {
            return base.Channel.SequenceGetInfoInXml(sequenceId);
        }
        
        public string GetLog() {
            return base.Channel.GetLog();
        }
        
        public string GetLogInHtml() {
            return base.Channel.GetLogInHtml();
        }
        
        public void TaskComplete(string TaskId) {
            base.Channel.TaskComplete(TaskId);
        }
    }
}
