//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Easis.Wfs.FlowSystemService.PES {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SequenceServiceSoap", Namespace="http://localhost/PES/SequenceService")]
    public partial class SequenceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SequenceEstimateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SequenceRunOperationCompleted;
        
        private System.Threading.SendOrPostCallback DebugOperationCompleted;
        
        private System.Threading.SendOrPostCallback SequenceAbortOperationCompleted;
        
        private System.Threading.SendOrPostCallback SequenceGetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SequenceGetInfoInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogInHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaskCompleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SequenceService() {
            this.Url = global::Easis.Wfs.FlowSystemService.Properties.Settings.Default.FlowSystemService_PES_SequenceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SequenceEstimateCompletedEventHandler SequenceEstimateCompleted;
        
        /// <remarks/>
        public event SequenceRunCompletedEventHandler SequenceRunCompleted;
        
        /// <remarks/>
        public event DebugCompletedEventHandler DebugCompleted;
        
        /// <remarks/>
        public event SequenceAbortCompletedEventHandler SequenceAbortCompleted;
        
        /// <remarks/>
        public event SequenceGetInfoCompletedEventHandler SequenceGetInfoCompleted;
        
        /// <remarks/>
        public event SequenceGetInfoInXmlCompletedEventHandler SequenceGetInfoInXmlCompleted;
        
        /// <remarks/>
        public event GetLogCompletedEventHandler GetLogCompleted;
        
        /// <remarks/>
        public event GetLogInHtmlCompletedEventHandler GetLogInHtmlCompleted;
        
        /// <remarks/>
        public event TaskCompleteCompletedEventHandler TaskCompleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/SequenceEstimate", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public SequenceEstimateResult SequenceEstimate(string sequenceRunXml) {
            object[] results = this.Invoke("SequenceEstimate", new object[] {
                        sequenceRunXml});
            return ((SequenceEstimateResult)(results[0]));
        }
        
        /// <remarks/>
        public void SequenceEstimateAsync(string sequenceRunXml) {
            this.SequenceEstimateAsync(sequenceRunXml, null);
        }
        
        /// <remarks/>
        public void SequenceEstimateAsync(string sequenceRunXml, object userState) {
            if ((this.SequenceEstimateOperationCompleted == null)) {
                this.SequenceEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSequenceEstimateOperationCompleted);
            }
            this.InvokeAsync("SequenceEstimate", new object[] {
                        sequenceRunXml}, this.SequenceEstimateOperationCompleted, userState);
        }
        
        private void OnSequenceEstimateOperationCompleted(object arg) {
            if ((this.SequenceEstimateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SequenceEstimateCompleted(this, new SequenceEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/SequenceRun", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SequenceRun(string sequenceRunXml) {
            this.Invoke("SequenceRun", new object[] {
                        sequenceRunXml});
        }
        
        /// <remarks/>
        public void SequenceRunAsync(string sequenceRunXml) {
            this.SequenceRunAsync(sequenceRunXml, null);
        }
        
        /// <remarks/>
        public void SequenceRunAsync(string sequenceRunXml, object userState) {
            if ((this.SequenceRunOperationCompleted == null)) {
                this.SequenceRunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSequenceRunOperationCompleted);
            }
            this.InvokeAsync("SequenceRun", new object[] {
                        sequenceRunXml}, this.SequenceRunOperationCompleted, userState);
        }
        
        private void OnSequenceRunOperationCompleted(object arg) {
            if ((this.SequenceRunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SequenceRunCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/Debug", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Debug() {
            this.Invoke("Debug", new object[0]);
        }
        
        /// <remarks/>
        public void DebugAsync() {
            this.DebugAsync(null);
        }
        
        /// <remarks/>
        public void DebugAsync(object userState) {
            if ((this.DebugOperationCompleted == null)) {
                this.DebugOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDebugOperationCompleted);
            }
            this.InvokeAsync("Debug", new object[0], this.DebugOperationCompleted, userState);
        }
        
        private void OnDebugOperationCompleted(object arg) {
            if ((this.DebugCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DebugCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/SequenceAbort", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SequenceAbort(ulong sequenceId) {
            this.Invoke("SequenceAbort", new object[] {
                        sequenceId});
        }
        
        /// <remarks/>
        public void SequenceAbortAsync(ulong sequenceId) {
            this.SequenceAbortAsync(sequenceId, null);
        }
        
        /// <remarks/>
        public void SequenceAbortAsync(ulong sequenceId, object userState) {
            if ((this.SequenceAbortOperationCompleted == null)) {
                this.SequenceAbortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSequenceAbortOperationCompleted);
            }
            this.InvokeAsync("SequenceAbort", new object[] {
                        sequenceId}, this.SequenceAbortOperationCompleted, userState);
        }
        
        private void OnSequenceAbortOperationCompleted(object arg) {
            if ((this.SequenceAbortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SequenceAbortCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/SequenceGetInfo", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public SequenceGetInfoResult SequenceGetInfo(ulong sequenceId) {
            object[] results = this.Invoke("SequenceGetInfo", new object[] {
                        sequenceId});
            return ((SequenceGetInfoResult)(results[0]));
        }
        
        /// <remarks/>
        public void SequenceGetInfoAsync(ulong sequenceId) {
            this.SequenceGetInfoAsync(sequenceId, null);
        }
        
        /// <remarks/>
        public void SequenceGetInfoAsync(ulong sequenceId, object userState) {
            if ((this.SequenceGetInfoOperationCompleted == null)) {
                this.SequenceGetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSequenceGetInfoOperationCompleted);
            }
            this.InvokeAsync("SequenceGetInfo", new object[] {
                        sequenceId}, this.SequenceGetInfoOperationCompleted, userState);
        }
        
        private void OnSequenceGetInfoOperationCompleted(object arg) {
            if ((this.SequenceGetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SequenceGetInfoCompleted(this, new SequenceGetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/SequenceGetInfoInXml", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SequenceGetInfoInXml(ulong sequenceId) {
            object[] results = this.Invoke("SequenceGetInfoInXml", new object[] {
                        sequenceId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SequenceGetInfoInXmlAsync(ulong sequenceId) {
            this.SequenceGetInfoInXmlAsync(sequenceId, null);
        }
        
        /// <remarks/>
        public void SequenceGetInfoInXmlAsync(ulong sequenceId, object userState) {
            if ((this.SequenceGetInfoInXmlOperationCompleted == null)) {
                this.SequenceGetInfoInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSequenceGetInfoInXmlOperationCompleted);
            }
            this.InvokeAsync("SequenceGetInfoInXml", new object[] {
                        sequenceId}, this.SequenceGetInfoInXmlOperationCompleted, userState);
        }
        
        private void OnSequenceGetInfoInXmlOperationCompleted(object arg) {
            if ((this.SequenceGetInfoInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SequenceGetInfoInXmlCompleted(this, new SequenceGetInfoInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/GetLog", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLog() {
            object[] results = this.Invoke("GetLog", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogAsync() {
            this.GetLogAsync(null);
        }
        
        /// <remarks/>
        public void GetLogAsync(object userState) {
            if ((this.GetLogOperationCompleted == null)) {
                this.GetLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogOperationCompleted);
            }
            this.InvokeAsync("GetLog", new object[0], this.GetLogOperationCompleted, userState);
        }
        
        private void OnGetLogOperationCompleted(object arg) {
            if ((this.GetLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogCompleted(this, new GetLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/GetLogInHtml", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogInHtml() {
            object[] results = this.Invoke("GetLogInHtml", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogInHtmlAsync() {
            this.GetLogInHtmlAsync(null);
        }
        
        /// <remarks/>
        public void GetLogInHtmlAsync(object userState) {
            if ((this.GetLogInHtmlOperationCompleted == null)) {
                this.GetLogInHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogInHtmlOperationCompleted);
            }
            this.InvokeAsync("GetLogInHtml", new object[0], this.GetLogInHtmlOperationCompleted, userState);
        }
        
        private void OnGetLogInHtmlOperationCompleted(object arg) {
            if ((this.GetLogInHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogInHtmlCompleted(this, new GetLogInHtmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/PES/SequenceService/TaskComplete", RequestNamespace="http://localhost/PES/SequenceService", ResponseNamespace="http://localhost/PES/SequenceService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TaskComplete(string TaskId) {
            this.Invoke("TaskComplete", new object[] {
                        TaskId});
        }
        
        /// <remarks/>
        public void TaskCompleteAsync(string TaskId) {
            this.TaskCompleteAsync(TaskId, null);
        }
        
        /// <remarks/>
        public void TaskCompleteAsync(string TaskId, object userState) {
            if ((this.TaskCompleteOperationCompleted == null)) {
                this.TaskCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaskCompleteOperationCompleted);
            }
            this.InvokeAsync("TaskComplete", new object[] {
                        TaskId}, this.TaskCompleteOperationCompleted, userState);
        }
        
        private void OnTaskCompleteOperationCompleted(object arg) {
            if ((this.TaskCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaskCompleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResult {
        
        private SequenceEstimateResultTime timeField;
        
        private SequenceEstimateResultStep[] stepField;
        
        private ulong idField;
        
        private stepResult resultField;
        
        /// <remarks/>
        public SequenceEstimateResultTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public SequenceEstimateResultStep[] step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultTime {
        
        private System.DateTime stampField;
        
        private ulong elapsedField;
        
        private ulong wastedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong wasted {
            get {
                return this.wastedField;
            }
            set {
                this.wastedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStep {
        
        private SequenceEstimateResultStepTime timeField;
        
        private SequenceEstimateResultStepCluster clusterField;
        
        private SequenceEstimateResultStepIN[] inField;
        
        private SequenceEstimateResultStepOut[] outField;
        
        private string taskIdField;
        
        private uint orderField;
        
        private stepResult resultField;
        
        /// <remarks/>
        public SequenceEstimateResultStepTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public SequenceEstimateResultStepCluster cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("in")]
        public SequenceEstimateResultStepIN[] @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("out")]
        public SequenceEstimateResultStepOut[] @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepTime {
        
        private ulong elapsedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepCluster {
        
        private string nameField;
        
        private string appField;
        
        private uint nodeCountField;
        
        private bool nodeCountFieldSpecified;
        
        private uint coreCountField;
        
        private bool coreCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string app {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint nodeCount {
            get {
                return this.nodeCountField;
            }
            set {
                this.nodeCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeCountSpecified {
            get {
                return this.nodeCountFieldSpecified;
            }
            set {
                this.nodeCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint coreCount {
            get {
                return this.coreCountField;
            }
            set {
                this.coreCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coreCountSpecified {
            get {
                return this.coreCountFieldSpecified;
            }
            set {
                this.coreCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepIN {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceEstimateResultStepOut {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum stepResult {
        
        /// <remarks/>
        completed,
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        notStarted,
        
        /// <remarks/>
        started,
        
        /// <remarks/>
        aborted,
        
        /// <remarks/>
        timeLimitExceeded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResult {
        
        private SequenceGetInfoResultTime timeField;
        
        private SequenceGetInfoResultStep[] stepField;
        
        private ulong idField;
        
        private stepResult resultField;
        
        /// <remarks/>
        public SequenceGetInfoResultTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public SequenceGetInfoResultStep[] step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultTime {
        
        private System.DateTime stampField;
        
        private ulong elapsedField;
        
        private ulong wastedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime stamp {
            get {
                return this.stampField;
            }
            set {
                this.stampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong wasted {
            get {
                return this.wastedField;
            }
            set {
                this.wastedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStep {
        
        private SequenceGetInfoResultStepTime timeField;
        
        private SequenceGetInfoResultStepCluster clusterField;
        
        private SequenceGetInfoResultStepIN[] inField;
        
        private SequenceGetInfoResultStepOut[] outField;
        
        private string taskIdField;
        
        private uint orderField;
        
        private stepResult resultField;
        
        /// <remarks/>
        public SequenceGetInfoResultStepTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public SequenceGetInfoResultStepCluster cluster {
            get {
                return this.clusterField;
            }
            set {
                this.clusterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("in")]
        public SequenceGetInfoResultStepIN[] @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("out")]
        public SequenceGetInfoResultStepOut[] @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public stepResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepTime {
        
        private ulong elapsedField;
        
        private ulong estimatedMinField;
        
        private ulong estimatedMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMin {
            get {
                return this.estimatedMinField;
            }
            set {
                this.estimatedMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong estimatedMax {
            get {
                return this.estimatedMaxField;
            }
            set {
                this.estimatedMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepCluster {
        
        private string nameField;
        
        private string appField;
        
        private uint nodeCountField;
        
        private bool nodeCountFieldSpecified;
        
        private uint coreCountField;
        
        private bool coreCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string app {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint nodeCount {
            get {
                return this.nodeCountField;
            }
            set {
                this.nodeCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nodeCountSpecified {
            get {
                return this.nodeCountFieldSpecified;
            }
            set {
                this.nodeCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint coreCount {
            get {
                return this.coreCountField;
            }
            set {
                this.coreCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coreCountSpecified {
            get {
                return this.coreCountFieldSpecified;
            }
            set {
                this.coreCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepIN {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SequenceGetInfoResultStepOut {
        
        private ulong internalIdField;
        
        private string storageIdField;
        
        private string slotNameField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storageId {
            get {
                return this.storageIdField;
            }
            set {
                this.storageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotName {
            get {
                return this.slotNameField;
            }
            set {
                this.slotNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SequenceEstimateCompletedEventHandler(object sender, SequenceEstimateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SequenceEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SequenceEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SequenceEstimateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SequenceEstimateResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SequenceRunCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DebugCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SequenceAbortCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SequenceGetInfoCompletedEventHandler(object sender, SequenceGetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SequenceGetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SequenceGetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SequenceGetInfoResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SequenceGetInfoResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SequenceGetInfoInXmlCompletedEventHandler(object sender, SequenceGetInfoInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SequenceGetInfoInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SequenceGetInfoInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLogCompletedEventHandler(object sender, GetLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLogInHtmlCompletedEventHandler(object sender, GetLogInHtmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogInHtmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogInHtmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TaskCompleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591